### ISSUE TITLE
Executable not found: experiments/train_model.py and experiments/test_model.py

### ISSUE THREAD

**Issue by wadkar** [dsg-bielefeld/deep_disfluency#1]
When I tried to run `experiments/InterSpeech_2015.py` it failed with:

```
#> python experiments/InterSpeech_2015.py
33 45 RNN
Traceback (most recent call last):
  File "experiments/InterSpeech_2015.py", line 172, in <module>
    subprocess.call(command)
  File "/Users/swadkar/.pyenv/versions/2.7.13/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/Users/swadkar/.pyenv/versions/2.7.13/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/Users/swadkar/.pyenv/versions/2.7.13/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
```
I believe the `experiments/InterSpeech_2015.py` tries to execute `experiments/test_model.py` (and/or `experiments/train_model.py`). However, there is no python executable at that location.

A quick look at the history of the file (ref: commits related to demo refactoring) indicate that `experiments/run_experiment.py` should be executed. However, the `test_filepath = None` indicates incorrect args to `run_experiment.py`'s argparser.

I just want to run the 2015 model, and see how it detects and repairs disfluencies. Specifically, if I have a sample sentence (e.g. `John likes, uh I mean, loves Mary`) how can I use the model to say, yield sentence with repaired disfluencies (e.g. `John loves Mary`)? Simply put:

```
echo 'John likes, uh I mean, loves Mary' | deep_disfluencies_repairer.py
# yields
John loves Mary
```

Also, any thoughts on porting the code to `python3`? I don't mind taking a stab at it because my production environment will always be `>=python3.5`. Moreover, `python2` will "expire" in 2020, which is not that far into future 🙊 .

Finally, does `deep_disfluency` _require_ `mumodo`? If so, any pointers on where to start on `mumodo`?

**Comment by julianhough** [comment]
Hi there, thanks for your interest!

I've just pushed quite a big change where you should see in the top level `demo.py` (or notebook `demo.ipynb`) that the first `DeepDisfluencyTagger` object does what you want and is our 2015 model. If you want to filter disfluencies out, as you say above, you have to do so based on the tags which are described in the `DeepDisfluencyTagger` class in `deep_disfluency.tagger.deep_tagger.py` to then remove words whose tags contain a `<rm` or `<e`. 

I will fix the experiments to reproduce the results in our papers in `InterSpeech_2015.py` and `EACL_2017.py` in the next few days.

I've removed the dependency on Mumodo so don't worry about that now.

For now, I'm sticking with Python 2, but yes, I take on board your concerns and will switch it to Python 3/make a branch soon and let you know.

**Comment by wadkar** [comment]
This is great! Thanks for the quick update.

I will take a look at `DeepDisfluencyTagger` and figure out my pipeline.

Looking forward to a `py3` branch when it happens!
