### ISSUE TITLE
The IBMWatsonAdapter is broken

### ISSUE THREAD

**Issue by Nagasaki45** [dsg-bielefeld/deep_disfluency#14]
After the last commit the adapter memory seems to be broken. With a minor change to the implicit test in `deep_disfluency.asr.ibm_watson` (see 30f2b98b6c8520445f999f630cc0952118b03af0) the issue is clearly visible. Here's the output of the test:

```
starting fake streaming
0.000892 seconds
{'start_time': 0, 'word': 'hello', 'end_time': 1, 'id': 0}
{'start_time': 1, 'word': 'my', 'end_time': 2, 'id': 1}
{'start_time': 2, 'word': 'name', 'end_time': 3, 'id': 2}
{'start_time': 0.5, 'word': 'hello', 'end_time': 1, 'id': 0}
{'start_time': 1, 'word': 'my', 'end_time': 2, 'id': 1}
{'start_time': 2, 'word': 'bame', 'end_time': 3, 'id': 2}
{'start_time': 3.4, 'word': 'once', 'end_time': 4, 'id': 3}
{'start_time': 4.2, 'word': 'upon', 'end_time': 4.6, 'id': 4}
{'start_time': 4.3, 'word': 'on', 'end_time': 4.8, 'id': 4}
finished fake streaming
```

Let me know if you want me to handle that.

**Comment by julianhough** [comment]
Hi Tom, this is precisely what should be coming out, no? This is the logic that makes the most sense in terms of incremental update to ongoing hypotheses (comments on the side):

{'start_time': 0, 'word': 'hello', 'end_time': 1, 'id': 0}       (new id)
{'start_time': 1, 'word': 'my', 'end_time': 2, 'id': 1}          (new id)
{'start_time': 2, 'word': 'name', 'end_time': 3, 'id': 2}      (new id)
{'start_time': 0.5, 'word': 'hello', 'end_time': 1, 'id': 0}    (id 0 word replaced as this new hypothesis overlaps the old id 0, other word updates chronologically after the old id 0 deleted, counter set to 1)
{'start_time': 1, 'word': 'my', 'end_time': 2, 'id': 1}          (new id)
{'start_time': 2, 'word': 'bame', 'end_time': 3, 'id': 2}      (new id)
{'start_time': 3.4, 'word': 'once', 'end_time': 4, 'id': 3}    (new id)
{'start_time': 4.2, 'word': 'upon', 'end_time': 4.6, 'id': 4} (new id)
{'start_time': 4.3, 'word': 'on', 'end_time': 4.8, 'id': 4}     (id 4 word replaced as it overlaps old id 4)

**Comment by Nagasaki45** [comment]
OK. I see. So when we update an ID, for example as a result of updated/overlapping timestamps or a different word, we will resend the following ones, right?
If so it's just me not understanding how the adapter should work. Let's close the ticket.

**Comment by Nagasaki45** [comment]
Sorry for closing too yearly. I still think it's broken.

Input example:
```
        [
            # First new
            [
                ('hello', 0, 1),
            ],
            # Old and add new
            [
                ('hello', 0, 1),
                ('my', 1, 2),
            ],
            # Updating old timestamp and add new
            [
                ('hello', 0.5, 1),
                ('my', 1, 2),
                ('name', 3, 4),
            ],
            # Updating old word
            [
                ('hello', 0.5, 1),
                ('your', 1, 2),
                ('name', 3, 4),
            ],
            # Multiple old and new ones with timestamp overlap
            [
                ('once', 3.4, 4),
                ('upon', 4.2, 4.6),
                ('on', 4.3, 4.8),
            ]
        ]
```

Expected output (only words and IDs):
```
        [
            ('hello', 0),
            ('my', 1),
            ('hello', 0),
            ('my', 1),
            ('name', 2),
            ('your', 1),
            ('name', 2),
            ('once', 2),
            ('upon', 3),
            ('on', 3),
        ]
```

Actual results:
```
{'start_time': 0, 'word': 'hello', 'end_time': 1, 'id': 0}
{'start_time': 0, 'word': 'hello', 'end_time': 1, 'id': 0}
{'start_time': 1, 'word': 'my', 'end_time': 2, 'id': 1}
{'start_time': 0.5, 'word': 'hello', 'end_time': 1, 'id': 0}
{'start_time': 1, 'word': 'my', 'end_time': 2, 'id': 1}
{'start_time': 3, 'word': 'name', 'end_time': 4, 'id': 2}
{'start_time': 0.5, 'word': 'hello', 'end_time': 1, 'id': 0}
{'start_time': 1, 'word': 'your', 'end_time': 2, 'id': 1}
{'start_time': 3, 'word': 'name', 'end_time': 4, 'id': 2}
{'start_time': 3.4, 'word': 'once', 'end_time': 4, 'id': 2}
{'start_time': 4.2, 'word': 'upon', 'end_time': 4.6, 'id': 3}
{'start_time': 4.3, 'word': 'on', 'end_time': 4.8, 'id': 3}
```

**Comment by Nagasaki45** [comment]
Here's my attempt to work on it. I'm not sure it's correct though, but I think the checks for updates are better.
https://github.com/dsg-bielefeld/deep_disfluency/pull/15

**Comment by julianhough** [comment]
Hi Tom, I've just fixed this myself and pushed. You rightly identified the redundancy of sending updates for identical words/time-stamps. Will check out your solution too.

**Comment by julianhough** [comment]
I like the idea of memory being a list, and using the conditions- much neater, though think they should reflect all the conditions of overlap in Allen's interval algebra [https://en.wikipedia.org/wiki/Allen%27s_interval_algebra], including those with identical start/finish times.

This gets more complicated however, as of course a new hypothesis can override multiple old ones. This why I think the backwards search technique is safer. First check if there is an exact match (using the start time dictionary look-up currently) and if so return None, if no exact match, backwards search through the hypotheses sorted by time (or back through the list), removing hypotheses until we get to the earliest updated word which overlaps the new hypotheses (the condition to identify the earliest overlapping update would be `old['start_time'] <= start_time and old['end_time'] <= end_time`.)

**Comment by julianhough** [comment]
I believe the the condition to identify the earliest overlapping update as your search backwards through the old updates would be `old['start_time'] <= start_time < old['end_time']`.

**Comment by Nagasaki45** [comment]
Just checked the last commit against my test and it works perfectly. I think we can close this issue and the pull request (#15).
