### ISSUE TITLE
non-incremental output generation

### ISSUE THREAD

**Issue by treena908** [dsg-bielefeld/deep_disfluency#25]
I saw in EACL 2017 paper that you presented non-incremental dialog-final result. I wanted to know, which method you used for that in deep_tagger class? I can see that for incremental tagging, incremental_output_from_file() method is used in deep_tagger.

can you please point out what folder to look into for  non-incremental dialog-final tagging?

**Comment by julianhough** [comment]
Hi there, thanks for your question on this:

The way the non-incremental dialogue-final tags are acquired is by running the notebook in deep_disfluency/experiments/analysis/EACL_2017/EACL_2017.ipynb 

The notebook takes the incremental output produced by the method you mention, along with the ground truth files, and produces a final output file from them, before evaluating that final output file.

Hope that helps!

Julian
