### ISSUE TITLE
Possible bug? `tag_utterance` for no POS and no timing data

### ISSUE THREAD

**Issue by wadkar** [dsg-bielefeld/deep_disfluency#3]
Just curious if you intended to reassign the utterance variable on [this line:](https://github.com/dsg-bielefeld/deep_disfluency/blob/master/deep_disfluency/tagger/deep_tagger.py#L523)
```py
def tag_utterance(self, utterance):
        """<snip>"""
        if not self.args.pos:  # no pos tag model
            utterance = [(w, None, t) for w, p, t in utterance]
            print "Warning: not using pos tags as not pos tag model"
        if not self.args.use_timing_data:
            utterance = [(w, p, None) for w, p, t in utterance]
            print "Warning: not using timing durations as no timing model"
        for w, p, t in utterance:
            if self.args.pos:
                self.tag_new_word(w, pos=p, timing=t)
        """<snip>"""
```
I was looking at using this method for tagging whole sentences and wondered what would happen if someone didn't provide both pos tags and timing data. Or is that something that is _not permissible_ within the overall experimental setup and configuration (i.e. config passed while instantiating the `DeepDisfluencyTagger` object)?

**Comment by julianhough** [comment]
Thanks for this. So yes, re-assignment isn't the best solution there, and I can change that.

The idea of it was to format it correctly for the 'mode' it's in (i.e. with or without POS, with or without timing). You don't have to pass it a timing value I don't think, but currently in all the models saved on this repo they require a POS input for the neural network `model` object. I will add in a feature to automatically tag the word if a POS tag is not given.

**Comment by wadkar** [comment]
Okay, gotcha!

Yep, adding a POS tagger as a feature would be nice. That way one can simply iterate through sentences from CoreNLP's `ssplit` annotator minus punctuation characters (because `data/tag_representations/swda_pos_rep.csv` doesn't include any POS for punctuation characters).
