### ISSUE TITLE
Add continuous integration with sanity tests on multiple platforms

### ISSUE THREAD

**Issue by Nagasaki45** [dsg-bielefeld/deep_disfluency#5]
In PR https://github.com/dsg-bielefeld/deep_disfluency/pull/4 @julianhough describes issues with multi-platform support. To my knowledge the best solution for these problems is to have a continuous integration server running tests on multiple environments. I have good experience with [travis-ci](https://travis-ci.org/), and they [support linux and osx](https://docs.travis-ci.com/user/multi-os/). If we must test on windows we can use [AppVeyor](https://www.appveyor.com/). I never used their services before so can't really tell how they are.

I think that we better start with writing some sanity tests to make sure we can load a tagger and tag a simple example, and run them on travis. We can always extend to other servises / tests later.

I can't implement these if you interested.
Looking forwards to hear your opinion.

**Comment by julianhough** [comment]
Hi Tom, as per the pull request, we're going to park this for now.
